# Generated by Django 2.2 on 2019-08-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('proapp', '0002_auto_20190810_2248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
