# Generated by Django 2.2 on 2019-08-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0004_userprofile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='slug',
        ),
    ]
