# Generated by Django 2.2 on 2019-08-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0005_remove_userprofile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
