# Generated by Django 2.2 on 2019-08-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0006_userprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dateOfBirth',
            field=models.DateField(),
        ),
    ]
