# Generated by Django 2.2 on 2019-08-11 06:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0007_auto_20190811_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dateOfBirth',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 11, 6, 8, 49, 294780, tzinfo=utc)),
        ),
    ]
