# Generated by Django 2.2 on 2019-08-11 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0008_auto_20190811_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dateOfBirth',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
