# Generated by Django 2.2 on 2019-08-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0010_remove_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='', upload_to='proapp/images'),
        ),
    ]
